_format_version: "3.0"
services:
  - name: my-wasm-service
    url: http://httpbin.org
    routes:
      - name: my-wasm-route
        paths: ["/"]
        filter_chains:
          - filters:
              - name: jq-filter
                config: >-
                  {
                    "Query": ".data | fromjson | .[] | select(.Priority == \"Urgent\") | .Id"
                  }
